### ISSUE TITLE
Networking breaks if placing 'api' service in 'host' networking mode

### ISSUE THREAD

**Issue by TheFockinFury** [bitfeed-project/bitfeed#58]
Hi there, I'm trying to get bitfeed running on a node that I built using the raspibolt guide, meaning bitcoin core etc. are running on the host machine, not in containers. I made some modifications to docker-compose.yml accordingly but can't seem to get the service to come up.

- If I leave the back end port as-is (5000) and do not modify networking setup, the client comes up but the back end can't connect to RPC due to that address being taken. This is expected as lnbits is already using that port. 
- If I modify port 5000 to something else (6000 in this case), the client comes up but the back end fails because the RPC connection was refused. This is also expected as the default bitfeed network shouldn't have access to the host.
- If I then modify the back end to use `network_mode: host`, the back end comes up, but this time the front end fails to come up:

`nginx: [emerg] host not found in upstream "api:6000" in /etc/nginx/conf.d/default.conf:42`

I'm sort of at a loss for how to resolve this. While the container is running (i.e. on the desired port but in the wrong network mode), i can see that default.conf does indeed have the expected entry. See below for the configs I'm working with. 

A few additional details:

- Bitcoin Core v.24.0.1
- Ubuntu Server 22.04 running in a Proxmox virtual machine
- Deployments being done through Portainer v2.17.1
- Docker v23.0.1

Is this a bug or user error?

-----

Values of `/etc/nginx/conf.d/default.conf `while the web container is running but the back end is unable to connect due to networking settings. Note that when I add `network_mode: host` to the `api` stanza in docker-compose, i can no longer access this default.conf because the web container keeps dying over and over.

```
root@82b17741b141:/etc/nginx/conf.d# cat default.conf
map $sent_http_content_type $expires {
    default                 off;
    text/css                max;
    text/json               max;
    application/javascript  max;
}

server {
    listen 80;

    root /var/www/bitfeed;
    index index.html;

    server_name client;

    location ~* \.(html)$ {
            add_header Cache-Control 'no-cache';
    }

    location /api {
            proxy_pass http://wsmonobackend;
            proxy_set_header        Host $http_host;
            proxy_set_header        X-Real-IP $remote_addr;
    }

    location /ws/txs {
            proxy_pass      http://wsmonobackend;
            proxy_http_version      1.1;
            proxy_set_header        Upgrade $http_upgrade;
            proxy_set_header        Connection "upgrade";
            proxy_set_header        Host $http_host;
            proxy_set_header        X-Real-IP $remote_addr;
    }

    location / {
            try_files $uri $uri/ /index.html;
            expires $expires;
    }
}

upstream wsmonobackend {
    server api:6000;
}
```

My `docker-compose.yml`
```
version: "2.1"

services:
  web:
    image: ghcr.io/bitfeed-project/bitfeed-client:v2.3.4
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      - "api"
    environment:
      TARGET: "docker"
      BACKEND_HOST: "api"
      BACKEND_PORT: "6000" #modified because port 5000 is already in use by another service
    ports:
      - "3080:80" #modified because port 3000 is already in use by another service

  api:
    image: ghcr.io/bitfeed-project/bitfeed-server:v2.3.4
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    network_mode: host #added network_mode: host so that I can access bitcoin RPC on local machine
    environment:
      PORT: "6000" #modified because port 5000 is already in use by another service
      BITCOIN_HOST: "127.0.0.1" #modified to point to localhost
      BITCOIN_ZMQ_RAWBLOCK_PORT: "28332"
      BITCOIN_ZMQ_RAWTX_PORT: "28333"
      BITCOIN_ZMQ_SEQUENCE_PORT: "28334"
      BITCOIN_RPC_PORT: "8332"
      BITCOIN_RPC_USER: "raspibolt" #using raspibolt RPC user
      BITCOIN_RPC_PASS: "[password]"
```

**Comment by TheFockinFury** [comment]
I'm going to resolve this because I figured it out and -- wait for it! -- it was user error.

Posting my solution here so that future rookies such as myself can learn from my mistakes as they figure out how to get an application running in docker to talk to bitcoin RPC on the host machine. First off, I was able to get things working using host mode in docker, but I felt icky doing that. So I decided to try to get docker to resolve to localhost via host.docker.internal. That sent me down a whole path and I learned a ton in the process.

Here's the important stuff in bitcoin.conf. The key point is that I needed to `rpcbind` to 0.0.0.0 and then also allow zmq connections on 0.0.0.0:port.

```
# Bitcoin daemon
server=1
txindex=1

# Network
listen=1
listenonion=1
proxy=127.0.0.1:9050
bind=127.0.0.1


# Connections
rpcport=8332
rpcbind=0.0.0.0     #is this safe? reckless!
rpcallowip=127.0.0.1     #allow RPC connections from localhost
rpcallowip=172.18.0.1/16     #allow RPC connections from the docker network on which the containers I'm trying to connect are running
rpcauth=user:passwordhash
zmqpubrawblock=tcp://0.0.0.0:28332     #need to accept zmq connections on 0.0.0.0 instead of 127.0.0.1
zmqpubrawtx=tcp://0.0.0.0:28333     #ditto
zmqpubsequence=tcp://0.0.0.0:28334     #ditto again
whitelist=download@127.0.0.1          # for Electrs
```

Here's the modified docker-compose.yml that works with the above bitcoin.conf configuration:

```
version: "2.1"

    services:
      web:
        image: ghcr.io/bitfeed-project/bitfeed-client:v2.3.4
        restart: on-failure
        stop_grace_period: 1m
        depends_on:
          - 'api'
        environment:
          TARGET: 'docker'
          BACKEND_HOST: 'api'
          BACKEND_PORT: '6000'  
        ports:
          - '3080:80' 
    
      api:
        image: ghcr.io/bitfeed-project/bitfeed-server:v2.3.4
        user: '1001:1001' #running as the bitcoin user (same user that runs bitcoind on the host)
        restart: on-failure
        stop_grace_period: 1m
        volumes:
          - '/home/bitcoin/.bitcoin:/bitcoin:ro'
        extra_hosts:
          - 'host.docker.internal:host-gateway'
        environment:
          PORT: '6000'  
          BITCOIN_HOST: 'host.docker.internal' 
          BITCOIN_ZMQ_RAWBLOCK_PORT: '28332'
          BITCOIN_ZMQ_RAWTX_PORT: '28333'
          BITCOIN_ZMQ_SEQUENCE_PORT: '28334'
          BITCOIN_RPC_PORT: '8332' #8332
          BITCOIN_RPC_COOKIE: /bitcoin/.cookie
          TARGET: personal
```
